[package]
name = "dataflow"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
buf_redux = "0.6.1"
evmap = "2.0.1"
fnv = "1.0.5"
itertools = "0.7.2"
regex = "0.2.2"
serde_derive = "1.0.8"
serde_json = "1.0.2"
slog = "2.0.6"
tarpc = "0.9.0"
tarpc-plugins = "0.2.0"
tokio-core = "0.1.8"
vec_map = { version = "0.8.0", features = ["eders"] }
hyper = "0.11.6"
futures = "0.1.16"

# need features
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
serde = { version = "1.0.8", features = ["rc"] }
timekeeper = {version = "0.3.0", default-features = false }

# git deps
petgraph = { git = "https://github.com/fintelia/petgraph", branch = "serde", features = ["serde"] }
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "fe7cdaa360c86bd4202e4065bc125ba5642439d2" }

# local deps
channel = { path = "../channel" }
core = { path = "../core" }

