[package]
name = "dataflow"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
buf_redux = "0.6.1"
evmap = "2.0.2"
fnv = "1.0.5"
itertools = "0.7.2"
regex = "0.2.2"
serde_derive = "1.0.8"
serde_json = "1.0.2"
slog = "2.2.2"
tarpc = "0.9.0"
tarpc-plugins = "0.2.0"
tokio-core = "0.1.8"
vec_map = { version = "0.8.0", features = ["eders"] }
hyper = "0.11.6"

# need features
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
petgraph = { version = "0.4.11", features = ["serde-1"] }
serde = { version = "1.0.8", features = ["rc"] }
timekeeper = {version = "0.3.0", default-features = false }

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "d8c96eae6fb0c5a9aba34fd49fcde459e0eea131" }

# local deps
channel = { path = "../channel" }
core = { path = "../core" }

