[package]
name = "dataflow"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
arccstr = "1.0.2"
arrayvec = "0.4.0"
buf_redux = "0.6.1"
evmap = "1.0.0"
fnv = "1.0.5"
itertools = "0.6.0"
mio = "0.6.9"
regex = "0.2.2"
serde_derive = "1.0.8"
serde_json = "1.0.2"
slog = "2.0.6"
tarpc = "0.9.0"
tarpc-plugins = "0.2.0"
tokio-core = "0.1.8"

# need features
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
chrono = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.8", features = ["rc"] }
timekeeper = {version = "0.3.0", default-features = false }
# git deps
petgraph = { git = "https://github.com/fintelia/petgraph", branch = "serde", features = ["serde"] }
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "af113901265d5d9add36ac8f7ff1abee75a220be" }
vec_map = { version = "0.8.0", features = ["eders"] }

# local deps
channel = { path = "../channel" }
core = { path = "../core" }

