dist: trusty
language: rust
rust:
  - nightly
cache: cargo
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all
  - cargo test --verbose
  - cargo test --verbose --manifest-path dataflow/Cargo.toml
