dist: trusty
language: rust
cache: cargo
rust:
  - nightly-2018-10-01
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - cargo test --verbose --all -- --test-threads=1
addons:
  apt:
    packages:
    - liblz4-dev
before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target/incremental
