version = 2

[uniform]
command = "cargo"
args = ["run", "--release", "--manifest-path", "noria-benchmarks/Cargo.toml", "--bin", "vote", "--", "--threads", "8", "localsoup"]
regexs = ["^(write\t50)\t([0-9.]+)", "^(read\t50)\t([0-9.]+)", "^(write\t95)\t([0-9.]+)", "^(read\t95)\t([0-9.]+)"]
lower_better = true

[uniform-unsharded]
command = "cargo"
args = ["run", "--release", "--manifest-path", "noria-benchmarks/Cargo.toml", "--bin", "vote", "--", "--threads", "8", "localsoup", "--shards=1"]
regexs = ["^(write\t50)\t([0-9.]+)", "^(read\t50)\t([0-9.]+)", "^(write\t95)\t([0-9.]+)", "^(read\t95)\t([0-9.]+)"]
lower_better = true

#[staged]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "vote", "--", "--avg", "--articles=100000", "--stage", "--runtime=30"]
#regexs = ["(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)"]
#
#[multiclient]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=30", "--getters=4"]
#regexs = ["^(avg GET): ([0-9.]+)", "(avg PUT): ([0-9.]+)", "^(cumavg GET): ([0-9.]+)"]

#[tx-bank]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "bank", "--", "--avg", "--accounts=1000", "--runtime=30", "-t=1"]
#regexs = ["(avg PUT): ([0-9.]+)"]

#[backfill]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "vote-stress", "--", "--articles=100000", "--votes=100000", "--runtime=10", "--stupid"]
#regexs = ["(RATE): ([0-9.]+)"]

#[vote-migration]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=60", "--migrate=30", "--stupid"]
#regexs = ["(Migration) completed in ([0-9.]+)s"]
#lower_better = true
#improvement_threshold = 0.5
#regression_threshold = 0.5

#[post-migration]
#command = "cargo"
#args = ["run", "--release", "--manifest-path", "benchmarks/Cargo.toml", "--bin", "vote", "--", "--avg", "--articles=100000", "--runtime=60", "--migrate=30", "--stupid"]
#regexs = ["avg (GET)\\+: ([0-9.]+)", "avg (PUT)\\+: ([0-9.]+)"]

[slack-aliases]
ms705 = "malte"
fintelia = "jonathan"
omegablitz = "aashish"
rtmrtmrtmrtm = "rtm"
larat7 = "laratimbo"
jmftrindade = "jmf"
ygina = "gina"
alanamarzoev = "marzoev"
jmbredenberg = "jamb"
