[package]
name = "trawler-mysql"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[features]
orchestration = ["tsunami", "rusoto_core", "rusoto_sts", "failure"]
default = []

[dependencies]
trawler = "0.6"
mysql_async = { git = "https://github.com/udoprog/mysql_async.git", rev = "f923dec2f2c2efbdcab0df6db275468a2be23fd4" }
tokio = "0.1"
clap = "2.31"
futures = "0.1"
chrono = "0.4"

failure = { version = "0.1.1", optional = true }
rusoto_core = { optional = true, version = "0.39" }
rusoto_sts = { optional = true, version = "0.39" }
tsunami = { optional = true, version = "0.8" }

[[bin]]
name = "lobsters"
path = "src/main.rs"

[[bin]]
name = "lobsters-ec2"
path = "src/ec2.rs"
required-features = ["orchestration"]
