[package]
name = "benchmarks"
version = "0.0.1"
authors = ["The Distributary Developers"]

[features]
b_memcached = ["memcached-rs"]
b_mysql = ["mysql"]
b_mssql = ["futures", "futures-state-stream", "tiberius", "tokio-core"]
b_netsoup = ["bincode", "net2", "bufstream"]
b_hybrid = ["mysql", "memcached-rs"]
default = ["b_netsoup", "b_memcached", "b_mysql", "b_mssql", "b_hybrid"]

[dependencies]
channel = { path = "../channel" }
chrono = { version = "0.4.0", features = ["serde"] }
distributary = { path = ".." }
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "af113901265d5d9add36ac8f7ff1abee75a220be" }
regex = "0.2.2"
slog = "2.0.6"
#slog = { version = "2.0.6", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = "2.0.1"
vec_map = { version = "0.8.0" }

# for benchmarks
# cli
clap = "2.25.0"
# distributions
rand = "0.3.15"
zipf = "0.2.0"
# sampling
hdrsample = "4.0.0"
# mssql
futures-state-stream = { version = "0.1", optional = true }
tiberius = { git = "https://github.com/ms705/tiberius/", optional = true }
# mysql
mysql = { version = "11.2.0", optional = true }
# memcached
memcached-rs = { git = "https://github.com/jonhoo/memcached-rs.git", branch = "expose-multi", optional = true }
# mio
mio = "0.6.9"
# netsoup
bincode = { version = "0.8.0", optional = true }
net2 = { version = "0.2.29", optional = true }
bufstream = { version = "0.1.3", optional = true }
# futures
futures = { version ="0.1.14", optional = true }
tokio-core = { version = "0.1.8", optional = true }

[[bin]]
name = "bank"
path = "bank/bank.rs"

[[bin]]
name = "vote"
path = "vote/vote.rs"

[[bin]]
name = "vote-server"
path = "vote/vote-server.rs"

[[bin]]
name = "vote-client"
path = "vote/vote-client.rs"

[[bin]]
name = "tpc_w"
path = "tpc_w/tpc_w.rs"

[[bin]]
name = "hotsoup"
path = "hotsoup/hotsoup.rs"

[[bin]]
name = "extract_hotcrp_queries"
path = "hotsoup/extract_queries.rs"

[[bin]]
name = "piazza"
path = "piazza/piazza.rs"

[[bin]]
name = "vote-new-fraction"
path = "vote/vote-new-fraction.rs"

[[bin]]
name = "vote-stress"
path = "vote/stress.rs"
